name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java-version: [8, 11, 17]
        scala-version: ["2.11.12", "2.12.15", "2.13.7"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version}}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: install jsdom
      run: npm install jsdom
    - name: Run tests
      env:
        JAVA_OPTS: -Xmx4g
      run: sbt ++${{ matrix.scala-version }} "set ThisBuild / Test / parallelExecution := false" compile Test/compile testQuick testQuick
